--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      midtermproject_ER_UPDATED.DM1
--
-- Date Created : Tuesday, March 11, 2025 22:50:51
-- Target DBMS : Snowflake
--

-- 
-- TABLE: BRIDGE_MOVIE 
--

CREATE TABLE BRIDGE_MOVIE(
    Bridge_Movie_SK    INTEGER        NOT NULL,
    GENRE_SK           INTEGER        NOT NULL,
    TITLE_SK           INTEGER        NOT NULL,
    DI_JOB_ID          VARCHAR(50)    NOT NULL,
    DI_LOAD_DATE       DATE           NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (Bridge_Movie_SK, GENRE_SK, TITLE_SK) 
)
;



-- 
-- TABLE: BRIDGE_TITLE_PERSONNEL 
--

CREATE TABLE BRIDGE_TITLE_PERSONNEL(
    BRIDGE_TITLE_PERSONNEL_SK    INTEGER          NOT NULL,
    TITLE_SK                     INTEGER          NOT NULL,
    PERSONNEL_SK                 INTEGER          NOT NULL,
    CATEGORY                     VARCHAR(50)      NOT NULL,
    JOB                          VARCHAR(1000),
    CHARACTERS                   VARCHAR(1000),
    DI_JOB_ID                    VARCHAR(50)      NOT NULL,
    DI_LOAD_DT                   DATE             NOT NULL,
    CONSTRAINT TCONST_NCONST_PK PRIMARY KEY (BRIDGE_TITLE_PERSONNEL_SK, TITLE_SK, PERSONNEL_SK) 
)
;



-- 
-- TABLE: DIM_DATE 
--

CREATE TABLE DIM_DATE(
    DATE_SK       INTEGER        NOT NULL,
    FULL_DATE     DATE           NOT NULL,
    DAY           VARCHAR(50),
    MONTH         VARCHAR(50),
    YEAR          INTEGER,
    DI_LOAD_DT    DATE           NOT NULL,
    DI_JOB_ID     VARCHAR(50)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (DATE_SK) 
)
;



-- 
-- TABLE: DIM_GENRE 
--

CREATE TABLE DIM_GENRE(
    GENRE_SK      INTEGER        NOT NULL,
    GENRE_NAME    VARCHAR(50)    NOT NULL,
    DI_JOB_ID     VARCHAR(50)    NOT NULL,
    DI_LOAD_DT    DATE           NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (GENRE_SK) 
)
;



-- 
-- TABLE: DIM_LANGUAGE 
--

CREATE TABLE DIM_LANGUAGE(
    LANGUAGE_SK      INTEGER         NOT NULL,
    LANGUAGE_NAME    VARCHAR(100)    NOT NULL,
    DI_JOB_ID        VARCHAR(50)     NOT NULL,
    DI_LOAD_DT       DATE            NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (LANGUAGE_SK) 
)
;



-- 
-- TABLE: DIM_LOCATION 
--

CREATE TABLE DIM_LOCATION(
    LOCATION_SK    INTEGER        NOT NULL,
    REGION         VARCHAR(50)    NOT NULL,
    DI_JOB_ID      VARCHAR(50)    NOT NULL,
    DI_LOAD_DT     DATE           NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (LOCATION_SK) 
)
;



-- 
-- TABLE: DIM_PERSONNEL 
--

CREATE TABLE DIM_PERSONNEL(
    PERSONNEL_SK          INTEGER         NOT NULL,
    NCONST                VARCHAR(50)     NOT NULL,
    PRIMARY_NAME          VARCHAR(100)    NOT NULL,
    BIRTH_YEAR            INTEGER,
    DEATH_YEAR            INTEGER,
    PRIMARY_PROFESSION    VARCHAR(100)    NOT NULL,
    KNOWN_FOR_TITLES      VARCHAR(100),
    DI_JOB_ID             VARCHAR(50)     NOT NULL,
    DI_LOAD_DT            DATE            NOT NULL,
    CONSTRAINT NCONST_PK PRIMARY KEY (PERSONNEL_SK) 
)
;



-- 
-- TABLE: DIM_TITLE 
--

CREATE TABLE DIM_TITLE(
    TITLE_SK          INTEGER         NOT NULL,
    TCONST            VARCHAR(50)     NOT NULL,
    PRIMARY_TITLE     VARCHAR(256)    NOT NULL,
    ORIGINAL_TITLE    VARCHAR(256)    NOT NULL,
    START_YEAR        INTEGER,
    END_YEAR          INTEGER,
    TITLE_TYPE        VARCHAR(200)    NOT NULL,
    IS_ADULT          SMALLINT        NOT NULL,
    DI_JOB_ID         VARCHAR(50)     NOT NULL,
    DI_LOAD_DT        DATE            NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (TITLE_SK) 
)
;



-- 
-- TABLE: Fact_Movie 
--

CREATE TABLE Fact_Movie(
    MOVIE_SK           INTEGER        NOT NULL,
    LANGUAGE_SK        INTEGER        NOT NULL,
    LOCATION_SK        INTEGER        NOT NULL,
    DATE_SK            INTEGER        NOT NULL,
    TITLE_SK           INTEGER        NOT NULL,
    TCONST             VARCHAR(50)    NOT NULL,
    PARENT_TCONST      VARCHAR(50),
    SEASON_NUMBER      INTEGER,
    EPISODE_NUMBER     CHAR(10),
    RUNTIME_MINUTES    INTEGER,
    DI_JOB_ID          VARCHAR(50)    NOT NULL,
    DI_LOAD_DT         DATE           NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (MOVIE_SK, LANGUAGE_SK, LOCATION_SK, DATE_SK, TITLE_SK) 
)
;



-- 
-- TABLE: Fact_Ratings 
--

CREATE TABLE Fact_Ratings(
    FACT_RATINGS_SK    INTEGER        NOT NULL,
    TITLE_SK           INTEGER        NOT NULL,
    AVERAGE_RATING     FLOAT,
    NUM_VOTES          INTEGER,
    DI_JOB_ID          VARCHAR(50)    NOT NULL,
    DI_LOAD_DT         DATE           NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (FACT_RATINGS_SK, TITLE_SK) 
)
;



-- 
-- TABLE: BRIDGE_MOVIE 
--

ALTER TABLE BRIDGE_MOVIE ADD CONSTRAINT RefDIM_TITLE16 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;

ALTER TABLE BRIDGE_MOVIE ADD CONSTRAINT RefDIM_GENRE19 
    FOREIGN KEY (GENRE_SK)
    REFERENCES DIM_GENRE(GENRE_SK)
;


-- 
-- TABLE: BRIDGE_TITLE_PERSONNEL 
--

ALTER TABLE BRIDGE_TITLE_PERSONNEL ADD CONSTRAINT RefDIM_TITLE17 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;

ALTER TABLE BRIDGE_TITLE_PERSONNEL ADD CONSTRAINT RefDIM_PERSONNEL18 
    FOREIGN KEY (PERSONNEL_SK)
    REFERENCES DIM_PERSONNEL(PERSONNEL_SK)
;


-- 
-- TABLE: Fact_Movie 
--

ALTER TABLE Fact_Movie ADD CONSTRAINT RefDIM_TITLE1 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;

ALTER TABLE Fact_Movie ADD CONSTRAINT RefDIM_LANGUAGE7 
    FOREIGN KEY (LANGUAGE_SK)
    REFERENCES DIM_LANGUAGE(LANGUAGE_SK)
;

ALTER TABLE Fact_Movie ADD CONSTRAINT RefDIM_LOCATION8 
    FOREIGN KEY (LOCATION_SK)
    REFERENCES DIM_LOCATION(LOCATION_SK)
;

ALTER TABLE Fact_Movie ADD CONSTRAINT RefDIM_DATE12 
    FOREIGN KEY (DATE_SK)
    REFERENCES DIM_DATE(DATE_SK)
;


-- 
-- TABLE: Fact_Ratings 
--

ALTER TABLE Fact_Ratings ADD CONSTRAINT RefDIM_TITLE9 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;


